server:
  shutdown: graceful
  port: 8004

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin@133.186.210.43:8004/eureka/
  instance:
    prefer-ip-address: true
    hostname: 133.186.210.43
