server:
  shutdown: graceful
  port: 8004

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true